### ISSUE TITLE
Renode crashes after running helloworld

### ISSUE THREAD

**Issue by vcnaveenkumar** [y2kbugger/baremetal-riscv-renode#2]
Hi Zak,
I was just exploring the kos on renode as you explained in your articles.

After setting everything up, i was able to get "kos>" shell and execute commands.

"?" worked fine, but when i enter "h", it prints "Hello world" and then renode crashes. I checked again and again, its crashing every time for "h" and "e", AFTER printing outputs.

Probable fix:

After digging a little deep, i saw that in the switch case of handle_interrupt() in baremetal.c, only case 4 (yield) has schedule and clear timer called, when i change the code to add those in case 3 (exit) like BELOW , "h" and "e" commands seem to work fine.

void handle_interrupt()
{
...
			switch (syscall_no) {
			case 2: // stop
				current_process->status = Stopped;
				break;
			case 3: // exit
				current_process->status = Dead;
				schedule_processes();
				clear_timer();
				break;
			case 4: // yield
				current_process->status = Ready;
				schedule_processes();
				clear_timer();
				break;
...
}

I don't know what exactly is the real source of the bug. Please check. Thanks for the articles and this repo.

**Comment by y2kbugger** [comment]
Can you let me know what commit you are using. I have actually been doing a
lot of changes recently, including fixing a bug in the context and
incorporating stubs for stdlib (newlib nano) so that I have access to
printf for example.

**Comment by vcnaveenkumar** [comment]
```
commit fcbbff3373fbaeab70657367ada9f0f60de3ab20 (origin/master, origin/HEAD)
Author: y2k <git@y2kbugger.com>
Date:   Sat Oct 7 00:21:50 2023 -0400

    Update backlog
```

I started just last week, so it should be the latest.

**Comment by y2kbugger** [comment]
I've moved some work in progress to a side branch, try it now with my
updated master branch.

**Comment by vcnaveenkumar** [comment]
Ok. I pulled the latest "kos" directory from the "interrupt_based_uart" branch.

Commands seem to be working fine now.

Thanks.

**Comment by vcnaveenkumar** [comment]
fixes in "interrupt_based_uart" branch

**Comment by y2kbugger** [comment]
@vcnaveenkumar feel free email me to chat about any part of system git@y2kbugger.com
